import type { GameEntity } from './gameAdapter'
import type { BridgeSpawnNpcMessage } from './gameBridge'
import { luaNpcEntityId, type GeneratedLuaNpcJson } from './luaNpcSchema'

const indent = (level: number): string => '  '.repeat(level)
const luaString = (value: string): string => JSON.stringify(value)

const renderStringArray = (values: string[], level: number): string => {
  if (values.length === 0) {
    return '{}'
  }

  return [
    '{',
    ...values.map((value) => `${indent(level + 1)}${luaString(value)},`),
    `${indent(level)}}`
  ].join('\n')
}

// legend-of-lua 호환 드롭인 데이터. 게임이 require로 불러 NPC를 스폰/등록할 수 있는 형태다
// (스폰·렌더 연결은 게임-쪽 몫 — 이번 범위는 이 산출물 생성까지). behavior는 my-sample-rpg의
// Lua 컨트롤러(wander-near-home/reply-with-message)와 같은 개념을 데이터로 전달한다.
export const renderGeneratedLuaNpcModule = (npc: GeneratedLuaNpcJson): string =>
  [
    '-- Generated by the Legend of Lua NPC editor',
    '-- 스폰/등록 배선은 게임-쪽 드롭인 몫(계약: docs/legend-of-lua-npc-contract.md).',
    'return {',
    `${indent(1)}entity_id = ${luaString(luaNpcEntityId(npc))},`,
    `${indent(1)}npc_id = ${luaString(npc.npc_id)},`,
    `${indent(1)}name = ${luaString(npc.name)},`,
    `${indent(1)}map = ${luaString(npc.map_id)},`,
    `${indent(1)}appearance = ${luaString(npc.appearance)},`,
    `${indent(1)}position = { x = ${npc.position.x}, y = ${npc.position.y} },`,
    `${indent(1)}dialogue = ${renderStringArray(npc.dialogue_lines, 1)},`,
    `${indent(1)}behavior = { type = ${luaString(npc.behavior.type)}, radius = ${npc.behavior.radius} },`,
    '}'
  ].join('\n')

// 생성 NPC를 에디터의 맵 엔티티로 변환한다 — 이걸 game.maps[map].entities에 넣으면 트리와
// 퀘스트 카탈로그(buildLuaQuestCatalog)가 "배치된 NPC"처럼 인식해, 곧바로 퀘스트 기버가 된다.
export const convertLuaNpcToGameEntity = (npc: GeneratedLuaNpcJson): GameEntity => ({
  id: luaNpcEntityId(npc),
  name: npc.name,
  kind: 'npc',
  mapId: npc.map_id
})

// legend-of-lua는 wander 반경을 픽셀로 쓰는데(맵 타일 16px), 에디터 radius는 타일 단위라 ×16 한다.
const TILE_SIZE = 16

// legend-of-lua의 src/levels/editorNPCs.lua 에 그대로 붙여넣을 스폰 항목(게임이 require해 스폰).
// 게임-쪽 spawnEditorNPCs가 editorNPCs[map] 배열을 읽어 spawnNPC(data)로 띄운다(npc.lua 참고).
// 위치는 nearPlayer=true로 "맵 진입 시 플레이어 바로 옆"에 띄운다 — LLM이 고른 임의 좌표가
// 물/벽 위로 가거나 화면 밖이 되는 걸 피하고, "생성하면 내 옆에 보인다"는 기대에 맞춘다.
export const renderEditorNpcSpawnEntry = (npc: GeneratedLuaNpcJson): string => {
  const radius =
    npc.behavior.type === 'wander' ? Math.round(npc.behavior.radius * TILE_SIZE) : 0

  return [
    `-- legend-of-lua/src/levels/editorNPCs.lua 의 editorNPCs[${luaString(npc.map_id)}] 배열에 추가:`,
    '{',
    `${indent(1)}name = ${luaString(npc.npc_id)},`,
    `${indent(1)}nearPlayer = true,`,
    `${indent(1)}appearance = ${luaString(npc.appearance)},`,
    `${indent(1)}dialogue = ${renderStringArray(npc.dialogue_lines, 1)},`,
    `${indent(1)}radius = ${radius},`,
    '},'
  ].join('\n')
}

// 라이브 브리지로 보낼 "한 줄짜리 Lua 테이블"(게임 pollEditorCommands가 loadstring으로 바로 로드).
// 직렬화/이스케이프를 여기(TS)서 끝내, host page 다리(vite.config.ts)는 문자열을 그대로 흘려보내면
// 된다 — 주입 스크립트 안에서 Lua를 만드느라 백슬래시 지옥에 빠지지 않게.
export const renderLuaNpcSpawnTable = (npc: GeneratedLuaNpcJson): string => {
  const radius =
    npc.behavior.type === 'wander' ? Math.round(npc.behavior.radius * TILE_SIZE) : 0
  const dialogue = npc.dialogue_lines.map((line) => luaString(line)).join(', ')
  return (
    `{ name=${luaString(npc.npc_id)}, map=${luaString(npc.map_id)}, ` +
    `appearance=${luaString(npc.appearance)}, dialogue={${dialogue}}, ` +
    `radius=${radius}, nearPlayer=true }`
  )
}

// 라이브 적용용 브리지 페이로드(kind:'spawn_npc'). '적용'이 이걸 패널 iframe(love.js)로 보내면
// host page 다리가 'spawn-npc:<lua>' 명령으로 게임에 전달해 spawnNPC한다(현재 플레이어 옆).
export const convertLuaNpcToSpawnBridgePayload = (
  npc: GeneratedLuaNpcJson,
  now: number
): BridgeSpawnNpcMessage => ({
  id: `spawn_npc-${npc.npc_id}-${now}`,
  kind: 'spawn_npc',
  generatedAt: now,
  lua: renderLuaNpcSpawnTable(npc),
  npc: {
    name: npc.npc_id,
    map: npc.map_id,
    appearance: npc.appearance,
    dialogue: npc.dialogue_lines,
    radius:
      npc.behavior.type === 'wander' ? Math.round(npc.behavior.radius * TILE_SIZE) : 0,
    nearPlayer: true
  }
})
