import type { GeneratedLuaQuestJson } from './luaQuestSchema'
import type { BridgeQuestMessage } from './gameBridge'

const indent = (level: number): string => '  '.repeat(level)
const luaString = (value: string): string => JSON.stringify(value)

const renderStringArray = (values: string[], level: number): string => {
  if (values.length === 0) {
    return '{}'
  }

  return [
    '{',
    ...values.map((value) => `${indent(level + 1)}${luaString(value)},`),
    `${indent(level)}}`
  ].join('\n')
}

const renderTarget = (
  target: GeneratedLuaQuestJson['objectives'][number]['target'],
  level: number
): string[] => {
  const lines: string[] = [`${indent(level)}target = {`]

  if (target.entityId) {
    lines.push(`${indent(level + 1)}entityId = ${luaString(target.entityId)},`)
  }
  if (target.mapId) {
    lines.push(`${indent(level + 1)}mapId = ${luaString(target.mapId)},`)
  }

  lines.push(`${indent(level)}}`)
  return lines
}

const renderObjective = (
  objective: GeneratedLuaQuestJson['objectives'][number],
  level: number
): string => [
  `${indent(level)}{`,
  `${indent(level + 1)}type = ${luaString(objective.type)},`,
  `${indent(level + 1)}label = ${luaString(objective.label)},`,
  `${indent(level + 1)}required = ${objective.required},`,
  ...renderTarget(objective.target, level + 1),
  `${indent(level)}}`
].join('\n')

const renderRewardItem = (
  item: GeneratedLuaQuestJson['rewards']['items'][number],
  level: number
): string => [
  `${indent(level)}{`,
  `${indent(level + 1)}label = ${luaString(item.label)},`,
  `${indent(level + 1)}quantity = ${item.quantity},`,
  `${indent(level)}}`
].join('\n')

export const renderGeneratedLuaQuestModule = (
  quest: GeneratedLuaQuestJson
): string => {
  const lines: string[] = [
    '-- Generated by the Legend of Lua quest editor',
    'return {',
    `${indent(1)}quest_id = ${luaString(quest.quest_id)},`,
    `${indent(1)}title = ${luaString(quest.title)},`,
    `${indent(1)}giver_npc_entity_id = ${luaString(quest.giver_npc_entity_id)},`,
    `${indent(1)}request_text = ${luaString(quest.request_text)},`,
    `${indent(1)}guide_text = ${luaString(quest.guide_text)},`,
    `${indent(1)}start_dialogue_lines = ${renderStringArray(quest.start_dialogue_lines, 1)},`,
    `${indent(1)}active_dialogue_lines = ${renderStringArray(quest.active_dialogue_lines, 1)},`,
    `${indent(1)}completion_dialogue_lines = ${renderStringArray(
      quest.completion_dialogue_lines,
      1
    )},`,
    `${indent(1)}objectives = {`
  ]

  quest.objectives.forEach((objective) => {
    lines.push(`${renderObjective(objective, 2)},`)
  })
  lines.push(`${indent(1)}},`)

  lines.push(`${indent(1)}rewards = {`)
  lines.push(`${indent(2)}gold = ${quest.rewards.gold},`)
  lines.push(`${indent(2)}experience = ${quest.rewards.experience},`)
  lines.push(`${indent(2)}items = {`)
  quest.rewards.items.forEach((item) => {
    lines.push(`${renderRewardItem(item, 3)},`)
  })
  lines.push(`${indent(2)}},`)
  lines.push(`${indent(1)}}`)
  lines.push('}')

  return lines.join('\n')
}

// 라이브 적용용 브리지 페이로드(kind:'quest'). 실행 중인 게임의 quest-runtime이 이 데이터를
// 받아 퀘스트를 등록·추적한다. Lua 코드 문자열과 같은 내용을 구조화 데이터로 보낸다.
export const convertLuaQuestToBridgePayload = (
  quest: GeneratedLuaQuestJson
): BridgeQuestMessage => ({
  id: `quest-${quest.quest_id}-${Date.now()}`,
  kind: 'quest',
  generatedAt: Date.now(),
  quest: {
    quest_id: quest.quest_id,
    title: quest.title,
    giver_entity_id: quest.giver_npc_entity_id,
    request_text: quest.request_text,
    guide_text: quest.guide_text,
    dialogue: {
      start: quest.start_dialogue_lines,
      active: quest.active_dialogue_lines,
      complete: quest.completion_dialogue_lines
    },
    objectives: quest.objectives.map((objective) => ({
      type: objective.type,
      label: objective.label,
      required: objective.required,
      target: {
        ...(objective.target.entityId
          ? { entityId: objective.target.entityId }
          : {}),
        ...(objective.target.mapId ? { mapId: objective.target.mapId } : {})
      }
    })),
    rewards: {
      gold: quest.rewards.gold,
      experience: quest.rewards.experience,
      items: quest.rewards.items.map((item) => ({
        label: item.label,
        quantity: item.quantity
      }))
    }
  }
})
