<?xml version="1.0" encoding="UTF-8"?>
<tileset
  version="1.8"
  tiledversion="1.8.2"
  name="town-32"
  tilewidth="32"
  tileheight="32"
  tilecount="560"
  columns="8"
>
  <image source="town-32.png" width="256" height="2240"/>
  <tile id="0" type="planter_tree_canopy"/>
  <tile id="1" type="planter_tree_shadow"/>
  <tile id="2" type="planter_stone_bowl"/>
  <tile id="3" type="banner_dark_top"/>
  <tile id="4" type="window_square_closed_top"/>
  <tile id="5" type="window_square_closed_shadow"/>
  <tile id="6" type="window_arch_closed_top_left"/>
  <tile id="7" type="window_arch_closed_top_right"/>
  <tile id="8" type="planter_box_left"/>
  <tile id="9" type="planter_box_center"/>
  <tile id="10" type="planter_box_right"/>
  <tile id="11" type="banner_dark_bottom"/>
  <tile id="12" type="window_square_closed_mid_left"/>
  <tile id="13" type="window_square_closed_mid_right"/>
  <tile id="14" type="window_arch_closed_bottom_left"/>
  <tile id="15" type="window_arch_closed_bottom_right"/>
  <tile id="16" type="planter_shadow_left"/>
  <tile id="17" type="planter_shadow_center"/>
  <tile id="18" type="planter_shadow_right"/>
  <tile id="19" type="window_square_closed_lower_left"/>
  <tile id="20" type="window_square_closed_lower_right"/>
  <tile id="21" type="window_square_closed_sill"/>
  <tile id="22" type="window_arch_closed_sill_left"/>
  <tile id="23" type="window_arch_closed_sill_right"/>
  <tile id="24" type="fountain_large_top_left"/>
  <tile id="25" type="fountain_large_top_center"/>
  <tile id="26" type="fountain_large_top_right"/>
  <tile id="27" type="flower_box_pink"/>
  <tile id="28" type="flower_box_green"/>
  <tile id="29" type="fountain_small_shadow"/>
  <tile id="30" type="fountain_small_top_left"/>
  <tile id="31" type="fountain_small_top_right"/>
  <tile id="32" type="fountain_large_mid_left"/>
  <tile id="33" type="fountain_large_mid_center"/>
  <tile id="34" type="fountain_large_mid_right"/>
  <tile id="35" type="wall_brick_gray_dark_fill"/>
  <tile id="36" type="wall_brick_gray_light_fill"/>
  <tile id="37" type="fountain_small_mid_shadow"/>
  <tile id="38" type="fountain_small_mid_left"/>
  <tile id="39" type="fountain_small_mid_right"/>
  <tile id="40" type="roof_red_shingle_top_left"/>
  <tile id="41" type="roof_red_shingle_top_center"/>
  <tile id="42" type="roof_red_shingle_top_right"/>
  <tile id="43" type="wall_cobble_fill"/>
  <tile id="44" type="wall_plaster_light_fill"/>
  <tile id="45" type="shadow_diagonal_cast_a"/>
  <tile id="46" type="fountain_small_lower_left"/>
  <tile id="47" type="fountain_small_lower_right"/>
  <tile id="48" type="roof_red_shingle_mid_left"/>
  <tile id="49" type="roof_red_shingle_mid_center"/>
  <tile id="50" type="roof_red_shingle_mid_right"/>
  <tile id="51" type="wall_brick_light_course_a"/>
  <tile id="52" type="wall_brick_gray_course_a"/>
  <tile id="53" type="shadow_diagonal_cast_b"/>
  <tile id="54" type="cobble_slope_fill"/>
  <tile id="55" type="wall_brick_light_course_b"/>
  <tile id="56" type="roof_red_shingle_bottom_left"/>
  <tile id="57" type="roof_red_shingle_bottom_center"/>
  <tile id="58" type="roof_red_shingle_bottom_right"/>
  <tile id="59" type="chimney_double_cap_left"/>
  <tile id="60" type="chimney_double_cap_right"/>
  <tile id="61" type="shadow_diagonal_cast_c"/>
  <tile id="62" type="shadow_diagonal_cast_d"/>
  <tile id="63" type="wall_brick_light_course_c"/>
  <tile id="64" type="roof_red_eave_left"/>
  <tile id="65" type="roof_red_eave_center"/>
  <tile id="66" type="roof_red_eave_right"/>
  <tile id="67" type="chimney_double_stack_left"/>
  <tile id="68" type="chimney_double_stack_right"/>
  <tile id="69" type="chimney_double_shadow"/>
  <tile id="70" type="fountain_small_base_left"/>
  <tile id="71" type="fountain_small_base_right"/>
  <tile id="72" type="roof_red_eave_shadow_left"/>
  <tile id="73" type="roof_red_eave_shadow_center"/>
  <tile id="74" type="roof_red_eave_shadow_right"/>
  <tile id="75" type="chimney_single_cap_left"/>
  <tile id="76" type="chimney_single_cap_right"/>
  <tile id="77" type="chimney_single_shadow"/>
  <tile id="78" type="fountain_small_pedestal_left"/>
  <tile id="79" type="fountain_small_pedestal_right"/>
  <tile id="80" type="wall_plaster_plain_top_left"/>
  <tile id="81" type="wall_plaster_plain_top_center"/>
  <tile id="82" type="wall_plaster_plain_top_right"/>
  <tile id="83" type="chimney_double_base_left"/>
  <tile id="84" type="chimney_double_base_right"/>
  <tile id="85" type="fountain_large_bottom_left"/>
  <tile id="86" type="fountain_large_bottom_center"/>
  <tile id="87" type="fountain_large_bottom_right"/>
  <tile id="88" type="wall_plaster_band_upper_left"/>
  <tile id="89" type="wall_plaster_band_upper_right"/>
  <tile id="90" type="roof_blue_shingle_strip_top_a"/>
  <tile id="91" type="roof_blue_shingle_strip_top_b"/>
  <tile id="92" type="roof_blue_shingle_strip_top_c"/>
  <tile id="93" type="roof_blue_shingle_strip_top_d"/>
  <tile id="94" type="roof_blue_gable_small_top_left"/>
  <tile id="95" type="roof_blue_gable_small_top_right"/>
  <tile id="96" type="wall_plaster_brick_upper_left"/>
  <tile id="97" type="wall_plaster_brick_upper_center"/>
  <tile id="98" type="wall_plaster_brick_upper_right"/>
  <tile id="99" type="roof_blue_shingle_strip_mid_a"/>
  <tile id="100" type="roof_blue_shingle_strip_mid_b"/>
  <tile id="101" type="roof_blue_shingle_strip_mid_c"/>
  <tile id="102" type="roof_blue_gable_small_upper_left"/>
  <tile id="103" type="roof_blue_gable_small_upper_right"/>
  <tile id="104" type="wall_plaster_grate_left"/>
  <tile id="105" type="wall_plaster_grate_center"/>
  <tile id="106" type="wall_plaster_grate_right"/>
  <tile id="107" type="roof_blue_shingle_strip_lower_a"/>
  <tile id="108" type="roof_blue_shingle_strip_lower_b"/>
  <tile id="109" type="roof_blue_shingle_strip_lower_c"/>
  <tile id="110" type="roof_blue_gable_small_middle_left"/>
  <tile id="111" type="roof_blue_gable_small_middle_right"/>
  <tile id="112" type="wall_plaster_plain_lower_left"/>
  <tile id="113" type="wall_plaster_plain_lower_center"/>
  <tile id="114" type="wall_plaster_plain_lower_right"/>
  <tile id="115" type="roof_blue_shingle_strip_bottom_a"/>
  <tile id="116" type="roof_blue_shingle_strip_bottom_b"/>
  <tile id="117" type="roof_blue_shingle_strip_bottom_c"/>
  <tile id="118" type="roof_blue_gable_small_lower_left"/>
  <tile id="119" type="roof_blue_gable_small_lower_right"/>
  <tile id="120" type="wall_plaster_base_left"/>
  <tile id="121" type="wall_plaster_base_center"/>
  <tile id="122" type="wall_plaster_base_right"/>
  <tile id="123" type="roof_blue_eave_left"/>
  <tile id="124" type="roof_blue_eave_center"/>
  <tile id="125" type="roof_blue_eave_right"/>
  <tile id="128" type="roof_red_gable_small_top_left"/>
  <tile id="129" type="roof_red_gable_small_top_right"/>
  <tile id="130" type="roof_blue_large_top_00"/>
  <tile id="131" type="roof_blue_large_top_01"/>
  <tile id="132" type="roof_blue_large_top_02"/>
  <tile id="133" type="roof_blue_large_top_03"/>
  <tile id="134" type="roof_blue_large_top_04"/>
  <tile id="135" type="roof_blue_large_top_05"/>
  <tile id="136" type="roof_blue_large_upper_00"/>
  <tile id="137" type="roof_blue_large_upper_01"/>
  <tile id="138" type="roof_blue_large_upper_02"/>
  <tile id="139" type="roof_blue_large_upper_03"/>
  <tile id="140" type="roof_blue_large_upper_04"/>
  <tile id="141" type="roof_blue_large_upper_05"/>
  <tile id="142" type="roof_blue_large_upper_06"/>
  <tile id="143" type="roof_blue_large_upper_07"/>
  <tile id="144" type="roof_blue_large_mid_00"/>
  <tile id="145" type="roof_blue_large_mid_01"/>
  <tile id="146" type="roof_blue_large_mid_02"/>
  <tile id="147" type="roof_blue_large_mid_03"/>
  <tile id="148" type="roof_blue_large_mid_04"/>
  <tile id="149" type="roof_blue_large_mid_05"/>
  <tile id="150" type="roof_blue_large_mid_06"/>
  <tile id="151" type="roof_blue_large_mid_07"/>
  <tile id="152" type="roof_blue_large_lower_00"/>
  <tile id="153" type="roof_blue_large_lower_01"/>
  <tile id="154" type="roof_blue_large_lower_02"/>
  <tile id="155" type="roof_blue_large_lower_03"/>
  <tile id="156" type="roof_blue_large_lower_04"/>
  <tile id="157" type="roof_blue_large_lower_05"/>
  <tile id="158" type="roof_blue_large_lower_06"/>
  <tile id="159" type="roof_blue_large_lower_07"/>
  <tile id="160" type="ladder_tall_left"/>
  <tile id="161" type="ladder_tall_right"/>
  <tile id="162" type="roof_blue_steep_strip_00"/>
  <tile id="163" type="roof_blue_steep_strip_01"/>
  <tile id="164" type="roof_blue_steep_strip_02"/>
  <tile id="165" type="roof_blue_steep_strip_03"/>
  <tile id="166" type="roof_blue_steep_strip_04"/>
  <tile id="167" type="roof_blue_steep_strip_05"/>
  <tile id="168" type="ladder_short_left"/>
  <tile id="169" type="ladder_short_right"/>
  <tile id="170" type="roof_blue_steep_peak_top_00"/>
  <tile id="173" type="roof_red_steep_peak_top_00"/>
  <tile id="174" type="roof_red_steep_peak_top_01"/>
  <tile id="176" type="roof_blue_steep_upper_00"/>
  <tile id="177" type="roof_blue_steep_upper_01"/>
  <tile id="178" type="roof_blue_steep_upper_02"/>
  <tile id="179" type="roof_blue_steep_upper_03"/>
  <tile id="180" type="roof_red_steep_upper_00"/>
  <tile id="181" type="roof_red_steep_upper_01"/>
  <tile id="182" type="roof_red_steep_upper_02"/>
  <tile id="183" type="roof_red_steep_upper_03"/>
  <tile id="184" type="roof_blue_steep_mid_00"/>
  <tile id="185" type="roof_blue_steep_mid_01"/>
  <tile id="186" type="roof_blue_steep_mid_02"/>
  <tile id="187" type="roof_blue_steep_mid_03"/>
  <tile id="188" type="roof_red_steep_mid_00"/>
  <tile id="189" type="roof_red_steep_mid_01"/>
  <tile id="190" type="roof_red_steep_mid_02"/>
  <tile id="191" type="roof_red_steep_mid_03"/>
  <tile id="192" type="roof_blue_steep_lower_00"/>
  <tile id="193" type="roof_blue_steep_lower_01"/>
  <tile id="194" type="roof_blue_steep_lower_02"/>
  <tile id="195" type="roof_blue_steep_lower_03"/>
  <tile id="196" type="roof_red_steep_lower_00"/>
  <tile id="197" type="roof_red_steep_lower_01"/>
  <tile id="198" type="roof_red_steep_lower_02"/>
  <tile id="199" type="roof_red_steep_lower_03"/>
  <tile id="200" type="roof_blue_steep_tip_00"/>
  <tile id="203" type="roof_blue_steep_tip_01"/>
  <tile id="204" type="roof_red_steep_tip_00"/>
  <tile id="207" type="roof_red_steep_tip_01"/>
  <tile id="208" type="roof_blue_peak_narrow_00"/>
  <tile id="209" type="roof_blue_peak_narrow_01"/>
  <tile id="210" type="roof_red_shingle_strip_top_00"/>
  <tile id="211" type="roof_red_shingle_strip_top_01"/>
  <tile id="212" type="roof_red_shingle_strip_top_02"/>
  <tile id="213" type="roof_red_shingle_strip_top_03"/>
  <tile id="214" type="roof_red_shingle_strip_top_04"/>
  <tile id="215" type="roof_red_shingle_strip_top_05"/>
  <tile id="216" type="roof_red_shingle_strip_mid_00"/>
  <tile id="217" type="roof_red_shingle_strip_mid_01"/>
  <tile id="218" type="roof_red_shingle_strip_mid_02"/>
  <tile id="219" type="roof_red_shingle_strip_mid_03"/>
  <tile id="220" type="roof_red_shingle_strip_mid_04"/>
  <tile id="221" type="roof_red_shingle_strip_mid_05"/>
  <tile id="222" type="roof_red_shingle_strip_mid_06"/>
  <tile id="223" type="roof_red_shingle_strip_mid_07"/>
  <tile id="224" type="roof_red_shingle_strip_lower_00"/>
  <tile id="225" type="roof_red_shingle_strip_lower_01"/>
  <tile id="226" type="roof_red_shingle_strip_lower_02"/>
  <tile id="227" type="roof_red_shingle_strip_lower_03"/>
  <tile id="228" type="roof_red_shingle_strip_lower_04"/>
  <tile id="229" type="roof_red_shingle_strip_lower_05"/>
  <tile id="230" type="roof_red_shingle_strip_lower_06"/>
  <tile id="231" type="roof_red_shingle_strip_lower_07"/>
  <tile id="232" type="roof_red_shingle_strip_eave_00"/>
  <tile id="233" type="roof_red_shingle_strip_eave_01"/>
  <tile id="234" type="roof_red_shingle_strip_eave_02"/>
  <tile id="235" type="roof_red_shingle_strip_eave_03"/>
  <tile id="236" type="roof_red_shingle_strip_eave_04"/>
  <tile id="237" type="roof_red_shingle_strip_eave_05"/>
  <tile id="238" type="roof_red_shingle_strip_eave_06"/>
  <tile id="239" type="roof_red_shingle_strip_eave_07"/>
  <tile id="240" type="roof_blue_peak_lower_00"/>
  <tile id="241" type="roof_blue_peak_lower_01"/>
  <tile id="242" type="roof_red_shingle_fill_wide_00"/>
  <tile id="243" type="roof_red_shingle_fill_wide_01"/>
  <tile id="244" type="roof_red_shingle_fill_wide_02"/>
  <tile id="245" type="roof_red_shingle_fill_wide_03"/>
  <tile id="246" type="roof_red_shingle_fill_wide_04"/>
  <tile id="247" type="roof_red_shingle_fill_wide_05"/>
  <tile id="248" type="roof_blue_peak_shadow_00"/>
  <tile id="249" type="roof_blue_peak_shadow_01"/>
  <tile id="250" type="roof_blue_shingle_fill_top_00"/>
  <tile id="251" type="roof_blue_shingle_fill_top_01"/>
  <tile id="252" type="roof_blue_shingle_fill_top_02"/>
  <tile id="253" type="roof_blue_shingle_fill_top_03"/>
  <tile id="254" type="roof_blue_shingle_fill_top_04"/>
  <tile id="255" type="roof_blue_shingle_fill_top_05"/>
  <tile id="256" type="roof_blue_shingle_fill_mid_00"/>
  <tile id="257" type="roof_blue_shingle_fill_mid_01"/>
  <tile id="258" type="roof_blue_shingle_fill_mid_02"/>
  <tile id="259" type="roof_blue_shingle_fill_mid_03"/>
  <tile id="260" type="roof_blue_shingle_fill_mid_04"/>
  <tile id="261" type="roof_blue_shingle_fill_mid_05"/>
  <tile id="262" type="roof_blue_shingle_fill_mid_06"/>
  <tile id="263" type="roof_blue_shingle_fill_mid_07"/>
  <tile id="264" type="roof_blue_shingle_fill_lower_00"/>
  <tile id="265" type="roof_blue_shingle_fill_lower_01"/>
  <tile id="266" type="roof_blue_shingle_fill_lower_02"/>
  <tile id="267" type="roof_blue_gable_cap_00"/>
  <tile id="268" type="roof_blue_gable_cap_01"/>
  <tile id="269" type="roof_blue_gable_cap_02"/>
  <tile id="270" type="roof_blue_gable_cap_03"/>
  <tile id="271" type="roof_blue_gable_cap_04"/>
  <tile id="272" type="roof_blue_gable_slope_00"/>
  <tile id="273" type="roof_blue_gable_slope_01"/>
  <tile id="274" type="roof_blue_gable_slope_02"/>
  <tile id="275" type="roof_blue_gable_slope_03"/>
  <tile id="276" type="gable_plaster_top_00"/>
  <tile id="277" type="gable_plaster_top_01"/>
  <tile id="278" type="roof_blue_gable_slope_04"/>
  <tile id="279" type="roof_blue_gable_slope_05"/>
  <tile id="280" type="roof_blue_gable_eave_00"/>
  <tile id="281" type="roof_blue_gable_eave_01"/>
  <tile id="282" type="roof_blue_gable_eave_02"/>
  <tile id="283" type="gable_plaster_mid_00"/>
  <tile id="284" type="gable_plaster_mid_01"/>
  <tile id="285" type="gable_plaster_mid_02"/>
  <tile id="286" type="gable_plaster_mid_03"/>
  <tile id="287" type="roof_blue_gable_eave_03"/>
  <tile id="288" type="roof_blue_gable_eave_04"/>
  <tile id="289" type="roof_blue_gable_eave_05"/>
  <tile id="290" type="wall_stone_arch_upper_00"/>
  <tile id="291" type="wall_stone_arch_upper_01"/>
  <tile id="292" type="wall_stone_arch_upper_02"/>
  <tile id="293" type="wall_stone_arch_upper_03"/>
  <tile id="294" type="wall_stone_arch_upper_04"/>
  <tile id="295" type="wall_stone_arch_upper_05"/>
  <tile id="297" type="banner_red_top"/>
  <tile id="298" type="wall_stone_arch_mid_00"/>
  <tile id="299" type="wall_stone_arch_mid_01"/>
  <tile id="300" type="facade_segment_300"/>
  <tile id="302" type="facade_segment_302"/>
  <tile id="303" type="wall_stone_arch_mid_02"/>
  <tile id="304" type="post_tall_base_00"/>
  <tile id="305" type="banner_red_bottom"/>
  <tile id="306" type="wall_plain_panel"/>
  <tile id="307" type="wall_stone_arch_lower_00"/>
  <tile id="308" type="ground_void_green_upper_00"/>
  <tile id="309" type="ground_void_green_upper_01"/>
  <tile id="310" type="ground_void_green_upper_02"/>
  <tile id="311" type="ground_void_green_upper_03"/>
  <tile id="312" type="post_tall_upper"/>
  <tile id="313" type="facade_segment_313"/>
  <tile id="314" type="wall_stone_arch_base_00"/>
  <tile id="315" type="ground_void_green_lower_00"/>
  <tile id="316" type="ground_void_green_lower_01"/>
  <tile id="317" type="ground_void_green_lower_02"/>
  <tile id="318" type="ground_void_green_lower_03"/>
  <tile id="319" type="ground_void_green_lower_04"/>
  <tile id="320" type="wall_cracked_slab_00"/>
  <tile id="321" type="clocktower_roof_top_00"/>
  <tile id="322" type="clocktower_roof_top_01"/>
  <tile id="323" type="clocktower_roof_top_02"/>
  <tile id="324" type="tree_small"/>
  <tile id="325" type="town_prop_325"/>
  <tile id="326" type="tree_large_canopy_00"/>
  <tile id="327" type="tree_large_canopy_01"/>
  <tile id="328" type="post_tall_mid"/>
  <tile id="329" type="clocktower_roof_mid_00"/>
  <tile id="330" type="clocktower_roof_mid_01"/>
  <tile id="332" type="bucket_metal"/>
  <tile id="333" type="tree_large_shadow_00"/>
  <tile id="334" type="tree_large_canopy_02"/>
  <tile id="335" type="tree_large_canopy_03"/>
  <tile id="336" type="town_prop_336"/>
  <tile id="337" type="clocktower_face_upper_00"/>
  <tile id="338" type="clocktower_face_upper_01"/>
  <tile id="339" type="streetlamp_unlit_top_00"/>
  <tile id="340" type="streetlamp_unlit_top_01"/>
  <tile id="341" type="streetlamp_unlit_top_02"/>
  <tile id="342" type="tree_large_canopy_04"/>
  <tile id="343" type="tree_large_canopy_05"/>
  <tile id="344" type="post_tall_lower"/>
  <tile id="345" type="clocktower_face_mid_00"/>
  <tile id="346" type="clocktower_face_mid_01"/>
  <tile id="347" type="clocktower_face_mid_02"/>
  <tile id="348" type="streetlamp_unlit_mid_00"/>
  <tile id="349" type="tree_large_trunk_00"/>
  <tile id="350" type="tree_large_trunk_01"/>
  <tile id="351" type="tree_large_trunk_02"/>
  <tile id="352" type="crate_rock"/>
  <tile id="353" type="clocktower_face_lower_00"/>
  <tile id="354" type="clocktower_face_lower_01"/>
  <tile id="355" type="clocktower_face_lower_02"/>
  <tile id="356" type="streetlamp_unlit_base_00"/>
  <tile id="357" type="sign_inn"/>
  <tile id="358" type="banner_red_lamp_top_00"/>
  <tile id="359" type="banner_red_lamp_top_01"/>
  <tile id="360" type="streetlamp_lit_top_left_cluster_00"/>
  <tile id="361" type="streetlamp_lit_top_left_cluster_01"/>
  <tile id="362" type="streetlamp_lit_top_left_cluster_02"/>
  <tile id="363" type="town_prop_363"/>
  <tile id="364" type="streetlamp_lit_top_right_cluster_00"/>
  <tile id="365" type="streetlamp_lit_top_right_cluster_01"/>
  <tile id="366" type="streetlamp_lit_top_right_cluster_02"/>
  <tile id="367" type="town_prop_367"/>
  <tile id="368" type="streetlamp_lit_mid_left_cluster_00"/>
  <tile id="369" type="streetlamp_lit_mid_left_cluster_01"/>
  <tile id="370" type="streetlamp_lit_mid_left_cluster_02"/>
  <tile id="371" type="town_prop_371"/>
  <tile id="372" type="streetlamp_lit_mid_right_cluster_00"/>
  <tile id="373" type="streetlamp_lit_mid_right_cluster_01"/>
  <tile id="374" type="streetlamp_lit_mid_right_cluster_02"/>
  <tile id="375" type="streetlamp_lit_mid_right_cluster_03"/>
  <tile id="376" type="crate_sword_left"/>
  <tile id="377" type="streetlamp_lit_base_left_00"/>
  <tile id="378" type="crate_sword_right"/>
  <tile id="379" type="clocktower_roof_alt_top_00"/>
  <tile id="380" type="clocktower_roof_alt_top_01"/>
  <tile id="381" type="clocktower_roof_alt_top_02"/>
  <tile id="382" type="streetlamp_lit_base_right_00"/>
  <tile id="383" type="streetlamp_lit_base_right_01"/>
  <tile id="384" type="banner_red_lamp_bottom_00"/>
  <tile id="385" type="banner_red_lamp_bottom_01"/>
  <tile id="386" type="banner_red_lamp_bottom_02"/>
  <tile id="387" type="town_prop_387"/>
  <tile id="388" type="clocktower_face_alt_upper_00"/>
  <tile id="389" type="clocktower_face_alt_upper_01"/>
  <tile id="390" type="market_canopy_peak_top_00"/>
  <tile id="391" type="market_canopy_peak_top_01"/>
  <tile id="392" type="market_canopy_band_top_00"/>
  <tile id="393" type="market_canopy_band_top_01"/>
  <tile id="394" type="market_canopy_band_top_02"/>
  <tile id="395" type="market_canopy_band_top_03"/>
  <tile id="396" type="clocktower_face_alt_lower_00"/>
  <tile id="397" type="clocktower_face_alt_lower_01"/>
  <tile id="398" type="market_canopy_peak_mid_00"/>
  <tile id="399" type="market_canopy_peak_mid_01"/>
  <tile id="400" type="market_canopy_band_mid_00"/>
  <tile id="401" type="market_canopy_band_mid_01"/>
  <tile id="402" type="market_canopy_band_mid_02"/>
  <tile id="403" type="market_prop_403"/>
  <tile id="404" type="clocktower_face_alt_base_00"/>
  <tile id="405" type="market_prop_405"/>
  <tile id="406" type="market_canopy_peak_lower_00"/>
  <tile id="407" type="market_canopy_peak_lower_01"/>
  <tile id="408" type="market_stall_back_top_00"/>
  <tile id="409" type="market_stall_back_top_01"/>
  <tile id="410" type="market_stall_back_top_02"/>
  <tile id="411" type="market_prop_411"/>
  <tile id="412" type="stairs_marble_upper_00"/>
  <tile id="413" type="stairs_marble_upper_01"/>
  <tile id="414" type="market_stall_front_top_00"/>
  <tile id="415" type="market_stall_front_top_01"/>
  <tile id="416" type="market_stall_back_leg_left_00"/>
  <tile id="417" type="market_stall_back_leg_left_01"/>
  <tile id="418" type="basket_empty"/>
  <tile id="419" type="barrel_open"/>
  <tile id="420" type="market_stall_back_leg_right_00"/>
  <tile id="421" type="market_stall_back_leg_right_01"/>
  <tile id="422" type="market_stall_front_leg_00"/>
  <tile id="423" type="market_stall_front_leg_01"/>
  <tile id="424" type="barrel_stack_shadow_00"/>
  <tile id="425" type="barrel_stack_shadow_01"/>
  <tile id="426" type="barrel_stack_shadow_02"/>
  <tile id="427" type="barrel_stack_shadow_03"/>
  <tile id="428" type="barrel_stack_shadow_04"/>
  <tile id="429" type="barrel_stack_shadow_05"/>
  <tile id="430" type="barrel_stack_shadow_06"/>
  <tile id="431" type="barrel_stack_shadow_07"/>
  <tile id="432" type="barrel_stack_a_top_left"/>
  <tile id="433" type="barrel_stack_a_top_center"/>
  <tile id="434" type="barrel_stack_a_top_right"/>
  <tile id="435" type="barrel_stack_b_top_left"/>
  <tile id="436" type="barrel_stack_b_top_center"/>
  <tile id="437" type="barrel_stack_b_top_right"/>
  <tile id="438" type="barrel_stack_c_top_left"/>
  <tile id="439" type="barrel_stack_c_top_right"/>
  <tile id="440" type="stairs_stone_left"/>
  <tile id="441" type="barrel_stack_a_mid_left"/>
  <tile id="442" type="barrel_stack_a_mid_center"/>
  <tile id="443" type="barrel_stack_a_mid_right"/>
  <tile id="444" type="barrel_stack_b_mid_left"/>
  <tile id="445" type="barrel_stack_b_mid_center"/>
  <tile id="446" type="barrel_stack_b_mid_right"/>
  <tile id="447" type="cliff_wall_fill"/>
  <tile id="448" type="stairs_stone_landing_left"/>
  <tile id="449" type="window_square_stone_left"/>
  <tile id="450" type="window_square_stone_center"/>
  <tile id="451" type="window_square_stone_right"/>
  <tile id="452" type="barrel_stack_lower_left"/>
  <tile id="453" type="barrel_stack_lower_center"/>
  <tile id="454" type="barrel_stack_lower_right"/>
  <tile id="455" type="cliff_wall_fill_alt"/>
  <tile id="456" type="grass_tuft_small"/>
  <tile id="457" type="grass_tuft_medium"/>
  <tile id="458" type="grass_tuft_cluster_a"/>
  <tile id="459" type="grass_tuft_cluster_b"/>
  <tile id="460" type="grass_tuft_cluster_c"/>
  <tile id="461" type="grass_tuft_cluster_d"/>
  <tile id="462" type="stump_small"/>
  <tile id="463" type="stump_large"/>
  <tile id="464" type="hedge_vertical_left"/>
  <tile id="465" type="stairs_stone_step_top_left"/>
  <tile id="466" type="stairs_stone_step_top_center"/>
  <tile id="467" type="stairs_stone_step_top_right"/>
  <tile id="468" type="stairs_stone_step_top_far_right"/>
  <tile id="469" type="hedge_large_top_left"/>
  <tile id="470" type="hedge_large_top_center"/>
  <tile id="471" type="hedge_large_top_right"/>
  <tile id="472" type="basket_empty_alt"/>
  <tile id="473" type="stairs_stone_step_mid_left"/>
  <tile id="474" type="stairs_stone_step_mid_center"/>
  <tile id="475" type="stairs_stone_step_mid_right"/>
  <tile id="476" type="stairs_stone_step_mid_far_right"/>
  <tile id="477" type="hedge_large_mid_left"/>
  <tile id="478" type="hedge_large_mid_center"/>
  <tile id="479" type="hedge_large_mid_right"/>
  <tile id="480" type="basket_empty_shadow"/>
  <tile id="481" type="stairs_stone_step_lower_left"/>
  <tile id="482" type="stairs_stone_step_lower_center"/>
  <tile id="483" type="stairs_stone_step_lower_right"/>
  <tile id="484" type="stairs_stone_step_lower_far_right"/>
  <tile id="485" type="hedge_large_lower_left"/>
  <tile id="486" type="hedge_large_lower_center"/>
  <tile id="487" type="hedge_large_lower_right"/>
  <tile id="488" type="stairs_stone_step_base_00"/>
  <tile id="489" type="stairs_stone_step_base_01"/>
  <tile id="490" type="stairs_stone_step_base_02"/>
  <tile id="491" type="stairs_stone_step_base_03"/>
  <tile id="492" type="basket_flowers"/>
  <tile id="493" type="ground_pit_small"/>
  <tile id="494" type="shadow_diagonal_ground_00"/>
  <tile id="495" type="shadow_diagonal_ground_01"/>
  <tile id="496" type="stairs_stone_step_base_lower_00"/>
  <tile id="497" type="stairs_stone_step_base_lower_01"/>
  <tile id="498" type="stairs_stone_step_base_lower_02"/>
  <tile id="499" type="stairs_stone_step_base_lower_03"/>
  <tile id="500" type="ground_pit_large_top"/>
  <tile id="501" type="planter_tree_bloom"/>
  <tile id="502" type="shadow_diagonal_ground_alt_00"/>
  <tile id="503" type="shadow_diagonal_ground_alt_01"/>
  <tile id="504" type="stairs_marble_lower_00"/>
  <tile id="505" type="stairs_marble_lower_01"/>
  <tile id="506" type="ground_sand_fill"/>
  <tile id="507" type="garden_round_top_00"/>
  <tile id="508" type="garden_round_top_01"/>
  <tile id="509" type="garden_round_top_02"/>
  <tile id="510" type="bush_round_top_00"/>
  <tile id="511" type="bush_round_top_01"/>
  <tile id="512" type="stairs_marble_mid_00"/>
  <tile id="513" type="stairs_marble_mid_01"/>
  <tile id="514" type="ground_cobble_fill"/>
  <tile id="515" type="garden_round_mid_00"/>
  <tile id="516" type="garden_round_mid_01"/>
  <tile id="517" type="garden_round_mid_02"/>
  <tile id="518" type="bush_round_bottom_00"/>
  <tile id="519" type="bush_round_bottom_01"/>
  <tile id="520" type="market_canopy_band_alt_top_00"/>
  <tile id="521" type="market_canopy_band_alt_top_01"/>
  <tile id="522" type="market_canopy_band_alt_top_02"/>
  <tile id="523" type="market_canopy_band_alt_top_03"/>
  <tile id="524" type="garden_round_lower_00"/>
  <tile id="525" type="garden_round_lower_01"/>
  <tile id="526" type="rocks_gray_cluster"/>
  <tile id="527" type="rocks_tan_cluster"/>
  <tile id="528" type="market_canopy_band_alt_bottom_00"/>
  <tile id="529" type="market_canopy_band_alt_bottom_01"/>
  <tile id="530" type="market_canopy_band_alt_bottom_02"/>
  <tile id="531" type="ground_cobble_fill_heavy_00"/>
  <tile id="532" type="ground_cobble_fill_heavy_01"/>
  <tile id="533" type="ground_cobble_fill_heavy_02"/>
  <tile id="534" type="ground_cobble_edge_left"/>
  <tile id="535" type="ground_pit_small_grass"/>
  <tile id="536" type="market_stall_back_bottom_00"/>
  <tile id="537" type="market_stall_back_bottom_01"/>
  <tile id="538" type="market_stall_back_bottom_02"/>
  <tile id="539" type="ground_cobble_fill_heavy_mid_00"/>
  <tile id="540" type="ground_cobble_fill_heavy_mid_01"/>
  <tile id="541" type="ground_cobble_fill_heavy_mid_02"/>
  <tile id="542" type="ground_cobble_edge_right"/>
  <tile id="543" type="ground_pit_large_bottom"/>
  <tile id="544" type="market_stall_front_bottom_00"/>
  <tile id="545" type="market_stall_front_bottom_01"/>
  <tile id="546" type="market_stall_front_bottom_02"/>
  <tile id="547" type="ground_cobble_fill_heavy_lower_00"/>
  <tile id="548" type="ground_cobble_fill_heavy_lower_01"/>
  <tile id="549" type="ground_cobble_fill_heavy_lower_02"/>
  <tile id="550" type="ground_cobble_fill_heavy_lower_03"/>
  <tile id="551" type="ground_pit_large_bottom_grass_00"/>
  <tile id="552" type="metal_plate_clean"/>
  <tile id="553" type="metal_plate_worn"/>
  <tile id="554" type="bottle_small_clear"/>
  <tile id="555" type="bottle_small_blue"/>
  <tile id="556" type="bottle_tall_clear"/>
  <tile id="557" type="bottle_tall_clear_alt"/>
  <tile id="558" type="shovel_small"/>
</tileset>
